#
# Variable donde se encuentran los datos finales y de procesos del comic.
#
[xml]$Global:comic = @(
'<?xml version="1.0" encoding="utf8"?>'
"<r>"
    "<CI> <!-- VARIABLES DEL COMIC. Son las que se usaran para escribir el fichero de metadatos comicinfo.xml-->" 
        "<Title>$null</Title>"
        "<Series>$null</Series>"
        "<Number>$null</Number>"
        "<Count>$null</Count>"
        "<Volume>$null</Volume>"
        "<Storyarc>$null</Storyarc>"
        "<Summary>$null</Summary>"
        "<Notes>$null</Notes>"
        "<Year>$null</Year>"
        "<Month>$null</Month>"
        "<Day>$null</Day>"
        "<Writer>$null</Writer>"
        "<Penciller>$null</Penciller>"
        "<Inker>$null</Inker>"
        "<Colorist>$null</Colorist>"
        "<Letterer>$null</Letterer>"
        "<CoverArtist>$null</CoverArtist>"
        "<Editor>$null</Editor>"
        "<Publisher>$null</Publisher>"
        "<Web>$null</Web>"                               
        "<PageCount>$null</PageCount>"
        "<Characters>$null</Characters>"
        "<Teams>$null</Teams>"
        "<Locations>$null</Locations>"
        "<ISBN>$null</ISBN>"
        "<comicvine_issue_id>$null</comicvine_issue_id>"
        "<comicvine_volume_id>$null</comicvine_volume_id>"
    "</CI>"
    "<DP> <!-- VARIABLES DE PROCESO. Son las variables que van a ser usadas por el script -->"
        "<dpserie>$null</dpserie>                               <!-- Nombre de la serie obtenido del directorio del comic -->"
        "<dpissue>$null</dpissue>                               <!-- Numero del comic en la serie obtenido del nombre del comic-->"
        "<dpfullname>$null</dpfullname>                         <!-- Ruta completa del comic -->"
        "<dpfullpath>$null</dpfullpath>                         <!-- Directorio completo del comic -->"
        "<dpseriespath>$null</dpseriespath>                     <!-- Directorio completo de la serie -->"
        "<dpcomicname>$null</dpcomicname>                       <!-- Nombre del comic sin extension -->"
        "<dpextension>$null</dpextension>                       <!-- Extension del fichero del comic -->"
        "<dpcomicyear>$null</dpcomicyear>                       <!-- Año obtenido del nombre del comic -->"
        "<dpseriespathyear>$null</dpseriespathyear>             <!-- Año obtenido del directorio del comic -->"
        "<dpseriespathpublisher>$null</dpseriespathpublisher>   <!-- Publisher obtenido del directorio del comic -->"
        "<dpocryear>$null</dpocryear>                           <!-- Año extraido mediante OCR de las imagenes -->"
        "<dpocrpublisher>$null</dpocrpublisher>                 <!-- Publisher extraido mediante OCR de las imagenes -->"
        "<dpocrisbn>$null</dpocrisbn>                           <!-- ISBN extraido mediante OCR de las imagenes -->"
        "<dpcomicvinematch>$null</dpcomicvinematch>             <!-- Se ha encontrado el comic en ComicVine -->"
    "</DP>"
"</r>"
)



